### ISSUE TITLE
Bogues à l'installation du module en français

### ISSUE THREAD

**Issue by cesagonchu** [JJDai54/glossaire#1]
3 Erreurs à l'installation :

1) Avertissement: Constant _MI_GLOSSAIRE_USER_PAGER_DESC already defined dans le fichier /modules/glossaire/language/french/modinfo.php ligne 150

2) Impossible d'installer glossaire. Erreur(s) :
Installation Glossaire
Invalid default value for 'cat_date_creation'

3) Avertissement: Undefined array key "100 Mo" dans le fichier /modules/glossaire/xoops_version.php ligne 292
Avertissement: Undefined array key "250 Mo" dans le fichier /modules/glossaire/xoops_version.php ligne 332

___
Ma config
Apache/2.4.52 (Ubuntu)
PHP version 8.1.2-1ubuntu2.10
MYSQL 8.0.32-0ubuntu0.22.04.2
Glossaire 1.2
XOOPS 2.5.11-Beta2 (dernière version FR https://www.frxoops.org/modules/newbb/viewtopic.php?viewmode=flat&type=&topic_id=38336&forum=14)

**Comment by JJDai54** [comment]
- points n°1 : réglé

- Point n° 2 : ma version de mysql est la 5.6, j'essaie d'installer un wamp avec mysql 8.0.32
c'es(t le type datetime qui pose problème dans le fichier mysal.sql:
  `cat_date_creation` datetime(6) NOT NULL DEFAULT '0000-00-00 00:00:00',
  l y a surement le même problème pour tous les champs de ce type.

- point n° 3: Je ne reproduit pas cette erreur, valeur remplacée pour l'instant en dur

**Comment by JJDai54** [comment]
point n°2 : l'erraur vient peut être du paramètre **sql_mode** de votre session inclue **NO_ZERO_DATE**.
ce qui potentiellement risque de poser d'autre soucis.

**Comment by JJDai54** [comment]
Point n° : remplacement de la valeur par default des champs   `datetime
  `cat_date_creation` datetime(6) NOT NULL DEFAULT '0000-00-00 00:00:00',
remplacé par 
  `cat_date_creation` datetime(6) NOT NULL DEFAULT '1970-01-01 00:00:00',,
