### ISSUE TITLE
Impossible d'insérer le modèle

### ISSUE THREAD

**Issue by cesagonchu** [JJDai54/glossaire#2]
L'installation du module se fait mais il y a des fichiers de "templates" qui ne s'installent pas dans la base de données.

```
ERREUR : Impossible d'insérer le modèle glossaire_admin_export.tpl dans la base de données.
ERREUR : Impossible d'insérer le modèle glossaire_entries.tpl dans la base de données.
ERREUR : Impossible d'insérer le modèle glossaire_entries_item-01.tpl dans la base de données.
ERREUR : Impossible d'insérer le modèle glossaire_entries_item-02.tpl dans la base de données.
ERREUR : Impossible d'insérer le modèle glossaire_entries_terms_links.tpl dans la base de données.
```

![image](https://user-images.githubusercontent.com/4613970/219960381-5fb3af06-d527-466b-8d4e-f129e94e1ccd.png)

___
Ma config
Apache/2.4.52 (Ubuntu)
PHP version 8.1.2-1ubuntu2.10
MYSQL 8.0.32-0ubuntu0.22.04.2
Glossaire 1.2
XOOPS 2.5.11-Beta2 (dernière version FR https://www.frxoops.org/modules/newbb/viewtopic.php?viewmode=flat&type=&topic_id=38336&forum=14)

**Comment by cesagonchu** [comment]
C'est peut-être dû au soucis d'apostrophe comme ici dans le fichier **glossaire_entries.tpl**

![image](https://user-images.githubusercontent.com/4613970/219960804-94a1b915-d0a7-498b-b0cf-24ad2402f1c0.png)

**Comment by JJDai54** [comment]
La je sèche, je ne reproduit pas l'erreur, et a priori ce n'est pas un problème d'apostrophe.

**Comment by cesagonchu** [comment]
J'ai réussi à faire importer le modèle **glossaire_entries_item-02.tpl** avec ces modifications :
 
 Ligne 20
 `<{* ---------- Affichage de boutons image pour gerer l'entree -----------*}>`
 replacé par
 `<{* ---------- Affichage de boutons image pour gerer l entree -----------*}>`
 
 Ligne 39
` <{* ---------- data de l'entree -----------*}>`
 replacé par 
` <{* ---------- data de l entree -----------*}>`
 
 Ligne 53
`  <{if $entry.email <>''}>`
replacé par 
`  <{if $entry.email}>`
  
Ligne 62
`<{* ---------- Affichage des boutons image pour gerer l'entree -----------*}>`
remplacé par
`<{* ---------- Affichage des boutons image pour gerer l entree -----------*}>`

Ligne 75
`<a href='entries.php?op=edit&ent_id=<{$entry.ent_id}>&start=<{$start}>&limit=<{$limit}>''>`
remplacé par
`<a href='entries.php?op=edit&ent_id=<{$entry.ent_id}>&start=<{$start}>&limit=<{$limit}>'>`

à toi de voir ce qui est bon ou pas car je ne suis pas développeuse.
Avec le logiciel Brackets on voit bien où se trouvent les erreurs, elles s'affichent en rouge.

**Comment by cesagonchu** [comment]
Les modèles s'insèrent correctement depuis la version Glossaire 1.2 beta 5.
