### ISSUE TITLE
Image clone manquante

### ISSUE THREAD

**Issue by cesagonchu** [JJDai54/glossaire#3]
Dans le fichier glossaire\admin\menu.php
	Ligne 67:     'icon' => $sysPathIcon32.'/clone.png',

Ce qui indique le chemin :
/Frameworks/moduleclasses/icons/32/clone.png

Hors l'image n'existe pas dans Xoops Core à cet endroit : 

https://github.com/XOOPS/XoopsCore25/tree/master/htdocs/Frameworks/moduleclasses/icons/32

![image](https://user-images.githubusercontent.com/4613970/220443522-51df6207-2f4f-4366-8528-d0a5310339f8.png)

**Comment by cesagonchu** [comment]
Apparemment l'image se situe ici :
modules\system\images\icons\default
quand on regarde le fichier system_blocks_item.tpl (modules\system\templates\admin\system_blocks_item.tpl) qui y fait référence, il est écrit ligne 26 :
 `<img src="<{xoAdminIcons clone.png}>" alt="<{$smarty.const._AM_SYSTEM_BLOCKS_CLONE}>"/></a>`

**Comment by JJDai54** [comment]
icône ajouter dans le module
