### ISSUE TITLE
categories.php inexistant

### ISSUE THREAD

**Issue by cesagonchu** [JJDai54/glossaire#4]
Côté administration, j'ai pu créer une catégorie et une entrée et j'ai configuré les droits mais lorsque je vais côté utilisateur et que je clique sur "Catégories" (/modules/glossaire/categories.php) ou sur "Soumettre les catégories" (modules/glossaire/categories.php?op=new), j'obtiens une page blanche qui indique "The requested URL was not found on this server.".

En effet, quand je vais sur mon ftp, le fichier categories.php n'existe pas.

**Comment by JJDai54** [comment]
Effectivement je n'ai pas géré les catégorie dans le front office estimant que les catégories devaient être crées plutôt dans l'admin pour ne pas se retrouver avec un profusion de catégories.
Je vais supprimé les menus correspondants pour l'instant, mais à voir si c'est nécéssaire.
Je laisse ouvert pour l'instant.

**Comment by JJDai54** [comment]
Finalement j'ai ajouté la gestion des catégories coté user.
